version: "1.0"
# Stages can help you organize your steps in stages
stages:
  - "clone"
  - "build"
  - "deploy"

steps:
  clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: "Hello"
    # CF_BRANCH value is auto set when pipeline is triggered
    # Learn more at codefresh.io/docs/docs/codefresh-yaml/variables/
    revision: "${{CF_BRANCH}}"
    git: "github"
    stage: "clone"

  build application:
    title: "build"
    type: "freestyle" # Run any command
    image: 'maven:3.5.2-jdk-8-alpine'
    working_directory: "${{clone}}/${{project}}" # Running command where code cloned
    commands:
      - mvn clean package -Dmaven.repo.local=/codefresh/volume/m2_repository -s settings.xml -Denvironment=${{environment}} -Denv=${{env}} "-DencryptionKey=${{encryptionKey}}" -DconnApp_clientId=${{connApp_clientId}} -DconnApp_clientSecret=${{connApp_clientSecret}} -DworkerType=${{worker_type}} -DnumberOfWorkers=${{number_of_workers}} -Dnexus_username=${{nexus_user}} -Dnexus_password=${{nexus_pass}}
    stage: "build"
    
  deploy application:
    title: "deploy"
    type: "freestyle" # Run any command
    image: 'maven:3.5.2-jdk-8-alpine'
    working_directory: "${{clone}}/${{project}}" # Running command where code cloned
    commands:
      - mvn -Dmaven.repo.local=/codefresh/volume/m2_repository -s settings.xml -Denvironment=${{environment}} -Denv=${{env}} "-DencryptionKey=${{encryptionKey}}" -DconnApp_clientId=${{connApp_clientId}} -DconnApp_clientSecret=${{connApp_clientSecret}} -DworkerType=${{worker_type}} -DnumberOfWorkers=${{number_of_workers}} -Dnexus_username=${{nexus_user}} -Dnexus_password=${{nexus_pass}} -Danypoint.platform.client_id=${{platform_id}} -Danypoint.platform.client_secret=${{platform_secret}} clean deploy -DmuleDeploy -DskipTests
    stage: "deploy"
